name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/unit

    - name: Run integration tests
      run: |
        pytest tests/integration

    - name: Run end-to-end tests
      run: |
        pytest tests/e2e

    - name: Generate coverage report
      run: |
        coverage run -m pytest tests
        coverage report -m
